name: chat_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  pull_to_refresh: ^2.0.0
  cupertino_icons: ^1.0.2
  socket_io_client: ^1.0.2
  provider: ^6.0.3
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
 